apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jupyterhub.name }}
  labels:
    {{- include "sqlflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jupyterhub.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.jupyterhub.service.servicePort }}
      protocol: TCP
  selector:
    {{- include "sqlflow.selectorLabels" . | nindent 4 }}