# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sqlflow-pv-claim
# spec:
#   accessModes:
#   - ReadOnlyMany
#   storageClassName: local-storage
#   resources:
#     requests:
#       storage: 10Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlflow-pv-claim
spec:
  accessModes:
  - ReadOnlyMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi