# On local run first: minikube mount /data/sqlflow-pv/:/data/sqlflow-pv/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlflow-pv 
  labels:
    type: local
spec:
  storageClassName: local-storage 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /datasets