apiVersion: v1
kind: Service
metadata:
  name: sqlflow-server
  labels:
    {{- include "sqlflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: server-port
      port: 80
      targetPort: 50051
      protocol: TCP
  selector:
    {{- include "sqlflow.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: sqlflow-jupyter
  labels:
    {{- include "sqlflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: jupyter-port
      port: 80
      targetPort: 8888
      protocol: TCP
  selector:
    {{- include "sqlflow.selectorLabels" . | nindent 4 }}

